'use client';
import { useEffect, useState, type CSSProperties } from 'react';
import { Truck, ShieldCheck, MessageCircle, Search, UserRound, ShoppingBag, ChevronLeft, ChevronRight, ChevronDown, Package, Heart, BadgeCheck, Wallet, SprayCan, Plus, Minus, Trash2, X } from 'lucide-react';
import { Sheet, SheetContent, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { products, money, filterProducts, updateCart, type Cart, type Product } from '@/lib/catalog';

function Photo({ x, y, w, h, label, className = '' }: { x: number; y: number; w: number; h: number; label: string; className?: string }) {
 return <div className={`photo ${className}`} role="img" aria-label={label} style={{ aspectRatio: `${w}/${h}`, "--photo-ratio": `${w}/${h}` } as CSSProperties}><img src="/soluna-reference.png" alt="" draggable={false} style={{ width: `${1222 / w * 100}%`, maxWidth: 'none', left: `${-x / w * 100}%`, top: `${-y / h * 100}%` }} /></div>;
}
const slides = [
 {line:'Fragancias que', ending:'dejan', accent:'huella.', subtitle:'Perfumes 100% originales.', filter:'Todos'},
 {line:'Tu esencia.', ending:'Tu', accent:'estilo.', subtitle:'Encuentra la fragancia que habla de ti.', filter:'Hombre'},
 {line:'Un aroma', ending:'para', accent:'recordar.', subtitle:'Descubre nuestra colección de mujer.', filter:'Mujer'},
];
const whatsapp = (message: string) => `https://wa.me/50686190302?text=${encodeURIComponent(message)}`;
const contactUrl = whatsapp('¡Hola, Soluna! Me gustaría recibir asesoría para elegir un perfume.');

export default function Home() {
 const [category,setCategory] = useState('Más vendidos');
 const [query,setQuery] = useState('');
 const [searchOpen,setSearchOpen] = useState(false);
 const [cartOpen,setCartOpen] = useState(false);
 const [accountOpen,setAccountOpen] = useState(false);
 const [cart,setCart] = useState<Cart>({});
 const [slide,setSlide] = useState(0);
 const [detail,setDetail] = useState<Product|null>(null);
 const [notice,setNotice] = useState('');
 const selected = filterProducts(category,query);
 const count = Object.values(cart).reduce((a,b)=>a+b,0);
 const total = products.reduce((sum,p)=>sum+(p.price??0)*(cart[p.id]??0),0);
 const hasUnpriced = products.some(p=>cart[p.id]&&!p.price);
 const order = '¡Hola, Soluna! Me gustaría consultar disponibilidad de estos perfumes:\n\n'+products.filter(p=>cart[p.id]).map(p=>`${cart[p.id]} × ${p.name} (${p.size}) — ${p.price?money(p.price*cart[p.id]):'Consultar precio'}`).join('\n')+`\n\nSubtotal estimado: ${money(total)}${hasUnpriced?' + productos por cotizar':''}.\nQuedo pendiente de la confirmación de disponibilidad y envío.`;
 function browse(value: string) {setCategory(value);setQuery('');setSearchOpen(false);document.getElementById('coleccion')?.scrollIntoView({behavior:'smooth'});}
 function add(id: string) {setCart(c=>updateCart(c,id,1));setNotice('Perfume agregado al carrito');}
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),2800);return()=>clearTimeout(timer)},[notice]);
 useEffect(()=>{
  type Tool = {name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown};
  const context=(document as Document & {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const tool:Tool={name:'filter_perfume_catalog',description:'Filtra el catálogo visible de Soluna por categoría y nombre. No modifica el carrito ni envía pedidos.',inputSchema:{type:'object',properties:{category:{type:'string',enum:['Todos','Hombre','Mujer','Unisex','Más vendidos','Nuevos']},query:{type:'string'}},required:['category'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){const value=input as {category:string;query?:string};if(!value||!['Todos','Hombre','Mujer','Unisex','Más vendidos','Nuevos'].includes(value.category)||(value.query!==undefined&&typeof value.query!=='string'))throw new Error('Filtro no válido');setCategory(value.category);setQuery(value.query??'');return {category:value.category,products:filterProducts(value.category,value.query??'').map(p=>({id:p.id,name:p.name,price:p.price}))};}};
  try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
  return()=>lifecycle.abort();
 },[]);
 return <main>
 <a className="skip-link" href="#coleccion">Saltar al catálogo</a>
 <header className="masthead"><div className="shipping"><Truck size={19} /> Envíos a todo Costa Rica <span>🇨🇷</span></div><a className="brand" href="#inicio" aria-label="Soluna, inicio"><Photo x={483} y={0} w={153} h={78} label="Soluna Fragrance" /></a><div className="header-actions"><a className="whatsapp-top" href={contactUrl} target="_blank" rel="noopener noreferrer"><MessageCircle size={18} /> +506 8619 0302</a><button aria-label="Buscar perfumes" onClick={()=>setSearchOpen(true)}><Search /></button><button className="account-button" aria-label="Información de compra" onClick={()=>setAccountOpen(true)}><UserRound/></button><button className="bag" aria-label={`Abrir carrito, ${count} productos`} onClick={()=>setCartOpen(true)}><ShoppingBag /><span>{count}</span></button></div></header>
 <nav aria-label="Navegación principal">{['Inicio','Perfumes','Hombre','Mujer','Unisex','Más vendidos','Nuevos','Contacto'].map((n,i)=><a key={n} className={(category===n||(category==='Todos'&&n==='Perfumes'))?'active':''} href={i===0?'#inicio':i===7?'#contacto':'#coleccion'} onClick={i>0&&i<7?(e)=>{e.preventDefault();browse(n==='Perfumes'?'Todos':n)}:undefined}>{n}{i===1&&<ChevronDown size={13}/>}</a>)}</nav>
 <section className={`hero slide-${slide}`} id="inicio" aria-roledescription="carrusel" aria-label="Colecciones Soluna"><Photo x={505} y={131} w={715} h={311} label="Bleu de Chanel sobre mármol oscuro con iluminación dorada" className="hero-photo"/><div className="hero-shade"/><div className="hero-copy" aria-live="polite"><p className="eyebrow">Soluna perfumería <span>—</span></p><h1>{slides[slide].line}<br/>{slides[slide].ending} <em>{slides[slide].accent}</em></h1><p className="hero-subtitle">{slides[slide].subtitle}</p><a className="gold-button" href="#coleccion" onClick={(e)=>{e.preventDefault();browse(slides[slide].filter)}}>Ver colección</a></div><button className="hero-arrow previous" aria-label="Colección anterior" onClick={()=>setSlide((slide+2)%3)}><ChevronLeft/></button><button className="hero-arrow next" aria-label="Siguiente colección" onClick={()=>setSlide((slide+1)%3)}><ChevronRight/></button><div className="dots">{slides.map((s,i)=><button key={s.accent} className={slide===i?'selected':''} aria-label={`Ver colección ${i+1}`} aria-pressed={slide===i} onClick={()=>setSlide(i)}/>)}</div></section>
 <section className="benefits" aria-label="Beneficios">{[[SprayCan,'100% originales','Garantizamos la autenticidad','de todos nuestros perfumes.'],[Truck,'Envíos rápidos','Recibe tu pedido en 24–48h','en todo Costa Rica.'],[ShieldCheck,'Compra segura','Tus compras están protegidas','con nosotros.'],[MessageCircle,'Atención personalizada','Escríbenos por WhatsApp','y te asesoramos.']].map(([Icon,title,a,b])=>{const I=Icon as typeof Truck;return <div className="benefit" key={String(title)}><I/><h3>{String(title)}</h3><p>{String(a)}<br/>{String(b)}</p></div>})}</section>
 <section className="categories content"><h2 className="section-title">Explora por categoría</h2><div className="category-grid">{[{name:'Hombre',x:59,w:350},{name:'Mujer',x:419,w:375},{name:'Unisex',x:805,w:350}].map(c=><a href="#coleccion" className="category" key={c.name} onClick={(e)=>{e.preventDefault();browse(c.name)}} aria-label={`Ver perfumes de ${c.name.toLowerCase()}`}><Photo x={c.x} y={632} w={c.w} h={183} label={`Colección ${c.name}`}/></a>)}</div></section>
 <section className="catalog content" id="coleccion"><h2 className="section-title">{query?`Resultados para “${query}”`:category==='Todos'?'Nuestra colección':category}</h2>{(category!=='Más vendidos'||query)&&<div className="filter-status"><span>{selected.length} {selected.length===1?'fragancia':'fragancias'}</span><button onClick={()=>browse('Más vendidos')}>Ver más vendidos <X size={14}/></button></div>}<div className="product-grid">{selected.map(p=><article className="product" key={p.id}><button className="product-photo-button" aria-label={`Ver ${p.name}`} onClick={()=>setDetail(p)}><Photo x={p.x} y={p.y??883} w={164} h={p.y?183:164} label={p.name}/></button><h3><button onClick={()=>setDetail(p)}>{p.name}</button></h3><p>{p.size}</p><strong>{p.price?money(p.price):'Consultar precio'}</strong><button className="add-button" onClick={()=>add(p.id)}>{cart[p.id]?`Agregar otro · ${cart[p.id]} en carrito`:'Agregar al carrito'}</button></article>)}</div>{selected.length===0&&<div className="empty-state"><Search/><h3>No encontramos esa fragancia</h3><p>Prueba con otra marca o explora toda la colección.</p><button className="gold-button" onClick={()=>browse('Todos')}>Ver todos los perfumes</button></div>}</section>
 <section className="contact-strip" id="contacto"><MessageCircle className="contact-icon"/><div><p>¿Dudas o consultas?</p><h2>Escríbenos por WhatsApp</h2><span>y te ayudamos a elegir tu fragancia ideal.</span></div><a className="gold-button" href={contactUrl} target="_blank" rel="noopener noreferrer">Escribir por WhatsApp</a></section>
 <footer>{[[Package,'Envío gratis','En compras mayores a ₡35,000'],[Wallet,'Paga seguro','Con SINPE Móvil o transferencia'],[BadgeCheck,'Garantía Soluna','Cambios en caso de ser necesario'],[Heart,'Clientes felices','Tu fragancia ideal te espera']].map(([Icon,title,text])=>{const I=Icon as typeof Truck;return <div key={String(title)}><I/><p><strong>{String(title)}</strong><span>{String(text)}</span></p></div>})}</footer>
 <div className="announcement" role="status" aria-live="polite">{notice&&<span><BadgeCheck size={19}/>{notice}<button onClick={()=>{setCartOpen(true);setNotice('')}}>Ver carrito</button></span>}</div>
 <Sheet open={cartOpen} onOpenChange={setCartOpen}><SheetContent className="cart-panel"><SheetTitle className="panel-title">Tu carrito <span>({count})</span></SheetTitle><SheetDescription>Una selección que deja huella.</SheetDescription>{count===0?<div className="empty-state"><ShoppingBag/><h3>Tu próxima fragancia te espera</h3><p>Explora la colección y agrega tus favoritos.</p><button className="gold-button" onClick={()=>{setCartOpen(false);browse('Todos')}}>Explorar perfumes</button></div>:<><div className="cart-items">{products.filter(p=>cart[p.id]).map(p=><div className="cart-item" key={p.id}><Photo x={p.x} y={p.y??883} w={164} h={p.y?183:164} label={p.name}/><div><h3>{p.name}</h3><p>{p.size} · {p.price?money(p.price):'Por cotizar'}</p><div className="quantity"><button aria-label={`Reducir cantidad de ${p.name}`} onClick={()=>setCart(c=>updateCart(c,p.id,-1))}><Minus size={14}/></button><span>{cart[p.id]}</span><button aria-label={`Aumentar cantidad de ${p.name}`} disabled={cart[p.id]>=99} onClick={()=>setCart(c=>updateCart(c,p.id,1))}><Plus size={14}/></button><button className="remove" aria-label={`Eliminar ${p.name}`} onClick={()=>setCart(c=>updateCart(c,p.id,-c[p.id]))}><Trash2 size={15}/></button></div></div></div>)}</div><div className="cart-bottom"><div className="subtotal"><span>Subtotal estimado</span><strong>{money(total)}</strong></div>{hasUnpriced&&<p>Más el precio de los productos por cotizar.</p>}<p>Disponibilidad, envío y total final se confirman por WhatsApp.</p><a className="gold-button" href={whatsapp(order)} target="_blank" rel="noopener noreferrer"><MessageCircle size={18}/> Consultar pedido por WhatsApp</a><button className="text-button" onClick={()=>setCartOpen(false)}>Seguir comprando</button></div></>}</SheetContent></Sheet>
 <Dialog open={searchOpen} onOpenChange={setSearchOpen}><DialogContent className="search-dialog"><DialogTitle className="panel-title">Encuentra tu fragancia</DialogTitle><DialogDescription>Busca por nombre o marca.</DialogDescription><form onSubmit={e=>{e.preventDefault();setCategory('Todos');setSearchOpen(false);document.getElementById('coleccion')?.scrollIntoView({behavior:'smooth'})}}><label htmlFor="perfume-search" className="sr-only">Nombre o marca del perfume</label><div className="search-input"><Search size={20}/><input id="perfume-search" placeholder="Prueba con Dior, Chanel…" value={query} onChange={e=>{setQuery(e.target.value);setCategory('Todos')}} autoComplete="off" autoFocus/></div><button className="gold-button" type="submit">Ver resultados</button></form></DialogContent></Dialog>
 <Dialog open={accountOpen} onOpenChange={setAccountOpen}><DialogContent className="search-dialog"><DialogTitle className="panel-title">Compra con atención personal</DialogTitle><DialogDescription>No necesitas una cuenta. Elige tus perfumes, agrégalos al carrito y consulta tu pedido por WhatsApp. Nuestro equipo te ayudará a confirmar la disponibilidad y coordinar el pago y envío.</DialogDescription><a className="gold-button" href={contactUrl} target="_blank" rel="noopener noreferrer">Hablar con Soluna</a></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={open=>{if(!open)setDetail(null)}}><DialogContent className="detail-dialog">{detail&&<><Photo x={detail.x} y={detail.y??883} w={164} h={detail.y?183:164} label={detail.name}/><DialogTitle className="panel-title">{detail.name}</DialogTitle><DialogDescription>{detail.category} · {detail.size} · Consulta la disponibilidad con nuestro equipo.</DialogDescription><strong className="detail-price">{detail.price?money(detail.price):'Consultar precio'}</strong><button className="gold-button" onClick={()=>{add(detail.id);setDetail(null);setCartOpen(true)}}>Agregar al carrito</button></>}</DialogContent></Dialog>
 </main>;
}

