'use client';
import { useEffect, useState, type CSSProperties } from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {useCart} from '@/components/cart-provider';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import productImages from '@/lib/product-images.json';
import { Truck, ShieldCheck, MessageCircle, Search, UserRound, ShoppingBag, ChevronLeft, ChevronRight, ChevronDown, Package, Heart, BadgeCheck, Wallet, SprayCan, Plus, Minus, Trash2, X } from 'lucide-react';
import { Sheet, SheetContent, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { products, womenBrands, menGroups, money, filterProducts, updateCart, concentration, type Cart, type Product } from '@/lib/catalog';

function Photo({ x, y, w, h, label, className = '' }: { x?: number; y: number; w: number; h: number; label: string; className?: string }) {
 if(x===undefined)return <div className="perfume-identity"><span>SOLUNA</span><i aria-hidden="true"/><strong>{label}</strong><small>PERFUMERÍA</small></div>;
 return <div className={`photo ${className}`} role="img" aria-label={label} style={{ aspectRatio: `${w}/${h}`, "--photo-ratio": `${w}/${h}` } as CSSProperties}><img src="/soluna-reference.png" alt="" draggable={false} style={{ width: `${1222 / w * 100}%`, maxWidth: 'none', left: `${-x / w * 100}%`, top: `${-y / h * 100}%` }} /></div>;
}
const slides = [
 {line:'Fragancias que', ending:'dejan', accent:'huella.', subtitle:'Perfumes 100% originales.', filter:'Todos'},
 {line:'Tu esencia.', ending:'Tu', accent:'estilo.', subtitle:'Encuentra la fragancia que habla de ti.', filter:'Hombre'},
 {line:'Un aroma', ending:'para', accent:'recordar.', subtitle:'Descubre nuestra colección de mujer.', filter:'Mujer'},
];
const whatsapp = (message: string) => `https://wa.me/50686190302?text=${encodeURIComponent(message)}`;
const contactUrl = whatsapp('¡Hola, Soluna! Me gustaría recibir asesoría para elegir un perfume.');

const collectionPaths:Record<string,string>={'Hombre':'/hombre','Mujer':'/mujer','Unisex':'/unisex','Todos':'/perfumes','Más vendidos':'/mas-vendidos','Nuevos':'/nuevos'};
function ProductPhoto({product}:{product:Product}){const image=(productImages as Record<string,{src:string}>)[product.id];return image?<div className="product-image"><img src={image.src} alt={product.name} loading="lazy"/></div>:<Photo x={product.x} y={product.y??883} w={164} h={product.y?183:164} label={product.name}/>;}
export default function Storefront({collection}:{collection?:string}) {
 const router=useRouter();
 const [category,setCategory] = useState(collection??'Más vendidos');
 const [query,setQuery] = useState('');
 const [searchOpen,setSearchOpen] = useState(false);
 const [cartOpen,setCartOpen] = useState(false);
 const [accountOpen,setAccountOpen] = useState(false);
 const [checkoutOpen,setCheckoutOpen] = useState(false);
 const [customer,setCustomer]=useState({name:'',phone:'',address:'',payment:'SINPE Móvil'});
 const {cart,setCart} = useCart();
 const [slide,setSlide] = useState(0);
 const [detail,setDetail] = useState<Product|null>(null);
 const [notice,setNotice] = useState('');
 const selected = filterProducts(category,query);
 const grouped = category==='Mujer'||category==='Hombre';
 const groups = category==='Mujer'?womenBrands:menGroups;
 const groupItems = (brand:string)=>selected.filter(p=>p.brand===brand||(brand==='Árabes'&&p.id==='men-odyssey-mandarin-sky'));
 useEffect(()=>{setCategory(collection??'Más vendidos');setQuery(new URLSearchParams(window.location.search).get('q')??'');},[collection]);
 useEffect(()=>{if(!collection&&(location.hash==='#hombre'||location.hash==='#mujer'))router.replace(location.hash==='#hombre'?'/hombre':'/mujer');},[collection,router]);
 const count = Object.values(cart).reduce((a,b)=>a+b,0);
 const pricedCount=products.filter(p=>cart[p.id]&&p.price!==null).length;
 const total = products.reduce((sum,p)=>sum+(p.price??0)*(cart[p.id]??0),0);
 const hasUnpriced = products.some(p=>cart[p.id]&&!p.price);
 const order = '¡Hola, Soluna! Me gustaría consultar disponibilidad de estos perfumes:\n\n'+products.filter(p=>cart[p.id]).map(p=>`${cart[p.id]} × ${p.name} (${concentration(p)} · ${p.size}) — ${p.price?money(p.price*cart[p.id]):'Consultar precio'}`).join('\n')+`\n\nSubtotal estimado: ${pricedCount?money(total):'Por confirmar'}${hasUnpriced?' + productos por cotizar':''}.\nQuedo pendiente de la confirmación de disponibilidad y envío.`;
 function browse(value:string){setSearchOpen(false);router.push(collectionPaths[value]??'/perfumes');}
 function add(id: string) {setCart(c=>updateCart(c,id,1));setNotice('Perfume agregado al carrito');}
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),2800);return()=>clearTimeout(timer)},[notice]);
 useEffect(()=>{
  type Tool = {name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown};
  const context=(document as Document & {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;
  if(!context?.registerTool)return;
  const lifecycle=new AbortController();
  const tool:Tool={name:'filter_perfume_catalog',description:'Filtra el catálogo visible de Soluna por categoría y nombre. No modifica el carrito ni envía pedidos.',inputSchema:{type:'object',properties:{category:{type:'string',enum:['Todos','Hombre','Mujer','Unisex','Más vendidos','Nuevos']},query:{type:'string'}},required:['category'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){const value=input as {category:string;query?:string};if(!value||!['Todos','Hombre','Mujer','Unisex','Más vendidos','Nuevos'].includes(value.category)||(value.query!==undefined&&typeof value.query!=='string'))throw new Error('Filtro no válido');router.push((collectionPaths[value.category]??'/perfumes')+'?q='+encodeURIComponent(value.query??''));return {category:value.category,products:filterProducts(value.category,value.query??'').map(p=>({id:p.id,name:p.name,price:p.price}))};}};
  try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}
  return()=>lifecycle.abort();
 },[]);
 const renderProduct=(p:Product)=><article className="product" key={p.id}><button className="product-photo-button" aria-label={`Ver ${p.name}`} onClick={()=>setDetail(p)}><ProductPhoto product={p}/></button><h3><button onClick={()=>setDetail(p)}>{p.name}</button></h3>{collection&&p.featured&&<span className="featured-label">★ Destacado</span>}{collection&&<p className="concentration">{concentration(p)}</p>}<p>{p.size}</p><strong>{p.price?money(p.price):'Consultar precio'}</strong><button className="add-button" onClick={()=>add(p.id)}>{cart[p.id]?`Agregar otro · ${cart[p.id]} en carrito`:'Agregar al carrito'}</button></article>;
 return <main>
 <a className="skip-link" href="#coleccion">Saltar al catálogo</a>
 <header className="masthead"><div className="shipping"><Truck size={19} /> Envíos a todo Costa Rica <span>🇨🇷</span></div><Link className="brand" href="/" aria-label="Soluna, inicio"><Photo x={483} y={0} w={153} h={78} label="Soluna Fragrance" /></Link><div className="header-actions"><a className="whatsapp-top" href={contactUrl} target="_blank" rel="noopener noreferrer"><MessageCircle size={18} /> +506 8619 0302</a><button aria-label="Buscar perfumes" onClick={()=>setSearchOpen(true)}><Search /></button><button className="account-button" aria-label="Información de compra" onClick={()=>setAccountOpen(true)}><UserRound/></button><button className="bag" aria-label={`Abrir carrito, ${count} productos`} onClick={()=>setCartOpen(true)}><ShoppingBag /><span>{count}</span></button></div></header>
 <nav aria-label="Navegación principal">{['Inicio','Perfumes','Hombre','Mujer','Unisex','Más vendidos','Nuevos','Contacto'].map(n=><Link key={n} className={(!collection&&n==='Inicio')||(collection===n)||(collection==='Todos'&&n==='Perfumes')?'active':''} href={n==='Inicio'?'/':n==='Contacto'?'#contacto':collectionPaths[n==='Perfumes'?'Todos':n]}>{n}{n==='Perfumes'&&<ChevronDown size={13}/>}</Link>)}</nav>
 {collection&&<div className="collection-intro content"><Link href="/">Inicio</Link><span>/</span><span>{collection==='Todos'?'Perfumes':collection}</span><p>Soluna Fragrance</p><h1>{collection==='Todos'?'Nuestra colección':collection==='Hombre'?'Perfumes de hombre':collection==='Mujer'?'Perfumes de mujer':collection}</h1></div>}
 {!collection&&<>
 <section className={`hero slide-${slide}`} id="inicio" aria-roledescription="carrusel" aria-label="Colecciones Soluna"><Photo x={505} y={131} w={715} h={311} label="Bleu de Chanel sobre mármol oscuro con iluminación dorada" className="hero-photo"/><div className="hero-shade"/><div className="hero-copy" aria-live="polite"><p className="eyebrow">Soluna perfumería <span>—</span></p><h1>{slides[slide].line}<br/>{slides[slide].ending} <em>{slides[slide].accent}</em></h1><p className="hero-subtitle">{slides[slide].subtitle}</p><a className="gold-button" href="#coleccion" onClick={(e)=>{e.preventDefault();browse(slides[slide].filter)}}>Ver colección</a></div><button className="hero-arrow previous" aria-label="Colección anterior" onClick={()=>setSlide((slide+2)%3)}><ChevronLeft/></button><button className="hero-arrow next" aria-label="Siguiente colección" onClick={()=>setSlide((slide+1)%3)}><ChevronRight/></button><div className="dots">{slides.map((s,i)=><button key={s.accent} className={slide===i?'selected':''} aria-label={`Ver colección ${i+1}`} aria-pressed={slide===i} onClick={()=>setSlide(i)}/>)}</div></section>
 <section className="benefits" aria-label="Beneficios">{[[SprayCan,'100% originales','Garantizamos la autenticidad','de todos nuestros perfumes.'],[Truck,'Envíos rápidos','Recibe tu pedido en 24–48h','en todo Costa Rica.'],[ShieldCheck,'Compra segura','Tus compras están protegidas','con nosotros.'],[MessageCircle,'Atención personalizada','Escríbenos por WhatsApp','y te asesoramos.']].map(([Icon,title,a,b])=>{const I=Icon as typeof Truck;return <div className="benefit" key={String(title)}><I/><h3>{String(title)}</h3><p>{String(a)}<br/>{String(b)}</p></div>})}</section>
 <section className="categories content"><h2 className="section-title">Explora por categoría</h2><div className="category-grid">{[{name:'Hombre',x:59,w:350},{name:'Mujer',x:419,w:375},{name:'Unisex',x:805,w:350}].map(c=><a href="#coleccion" className="category" key={c.name} onClick={(e)=>{e.preventDefault();browse(c.name)}} aria-label={`Ver perfumes de ${c.name.toLowerCase()}`}><Photo x={c.x} y={632} w={c.w} h={183} label={`Colección ${c.name}`}/></a>)}</div></section>
 </>}
 <section className={`catalog content ${collection?"collection-page":""}`} id="coleccion"><h2 className="section-title">{query?`Resultados para “${query}”`:category==='Todos'?'Nuestra colección':category}</h2>{(category!=='Más vendidos'||query)&&<div className="filter-status"><span>{selected.length} {selected.length===1?'fragancia':'fragancias'}</span><button onClick={()=>browse('Más vendidos')}>Ver más vendidos <X size={14}/></button></div>}{grouped&&<div className="collection-tools"><label className="collection-search"><Search size={18}/><input aria-label={`Buscar perfumes de ${category.toLowerCase()}`} placeholder="Buscar perfume o marca…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Limpiar búsqueda" onClick={()=>setQuery('')}><X size={16}/></button>}</label><div className="brand-links" aria-label="Ir a una marca">{groups.map((g,i)=>groupItems(g.brand).length?<a key={g.brand} href={`#marca-${i}`} onClick={e=>{e.preventDefault();document.getElementById(`marca-${i}`)?.scrollIntoView({behavior:'smooth'})}}>{g.brand}</a>:null)}</div></div>}{grouped?groups.map((g,i)=>{const items=groupItems(g.brand);return items.length?<section className="brand-section" key={g.brand} id={`marca-${i}`}><header><span>{String(i+1).padStart(2,'0')}</span><h3>{g.brand}</h3><small>{items.length} fragancias</small></header><div className="product-grid brand-products">{items.map(renderProduct)}</div></section>:null}):<div className="product-grid">{selected.map(renderProduct)}</div>}{selected.length===0&&<div className="empty-state"><Search/><h3>No encontramos esa fragancia</h3><p>Prueba con otra marca o explora toda la colección.</p><button className="gold-button" onClick={()=>browse('Todos')}>Ver todos los perfumes</button></div>}</section>
 <section className="contact-strip" id="contacto"><MessageCircle className="contact-icon"/><div><p>¿Dudas o consultas?</p><h2>Escríbenos por WhatsApp</h2><span>y te ayudamos a elegir tu fragancia ideal.</span></div><a className="gold-button" href={contactUrl} target="_blank" rel="noopener noreferrer">Escribir por WhatsApp</a></section>
 <footer className="site-footer"><section className="about-soluna"><h2>Sobre Soluna</h2><p>Soluna Perfumería nace con una misión clara: ofrecer perfumería 100% original a los mejores precios, para que disfrutar de grandes fragancias sea más accesible.</p><p>Seleccionamos cuidadosamente cada uno de nuestros perfumes para garantizar autenticidad, calidad y confianza en cada compra. Trabajamos para ofrecer precios competitivos sin sacrificar la calidad del producto.</p><p>En Soluna creemos que un buen perfume no solo es una fragancia, sino una forma de expresar quién eres y dejar una huella.</p><strong>Perfumería original. Precios que hacen la diferencia.</strong></section><section><h3>Métodos de pago</h3><p>SINPE Móvil</p><p>Tarjeta de débito / crédito</p><h3>Envíos</h3><p>Mensajería privada</p><p>A todo Costa Rica</p></section><section><h3>Redes sociales</h3><a href="https://www.instagram.com/solunacr/" target="_blank" rel="noopener noreferrer">Instagram · @Solunacr ↗</a><h3>Contacto</h3><a href={contactUrl} target="_blank" rel="noopener noreferrer">WhatsApp · 8619 0302</a><a href="tel:+50686190302">+506 8619 0302</a></section><div className="footer-signature"><span>Soluna Fragrance</span><span>solunafragrance.com</span></div></footer>
 <a className="floating-whatsapp" href={contactUrl} target="_blank" rel="noopener noreferrer" aria-label="Consultar o comprar por WhatsApp"><MessageCircle/></a>
 <div className="announcement" role="status" aria-live="polite">{notice&&<span><BadgeCheck size={19}/>{notice}<button onClick={()=>{setCartOpen(true);setNotice('')}}>Ver carrito</button></span>}</div>
 <Sheet open={cartOpen} onOpenChange={setCartOpen}><SheetContent className="cart-panel"><SheetTitle className="panel-title">Tu carrito <span>({count})</span></SheetTitle><SheetDescription>Una selección que deja huella.</SheetDescription>{count===0?<div className="empty-state"><ShoppingBag/><h3>Tu próxima fragancia te espera</h3><p>Explora la colección y agrega tus favoritos.</p><button className="gold-button" onClick={()=>{setCartOpen(false);browse('Todos')}}>Explorar perfumes</button></div>:<><div className="cart-items">{products.filter(p=>cart[p.id]).map(p=><div className="cart-item" key={p.id}><ProductPhoto product={p}/><div><h3>{p.name}</h3><p>{p.size} · {p.price?money(p.price):'Por cotizar'}</p><div className="quantity"><button aria-label={`Reducir cantidad de ${p.name}`} onClick={()=>setCart(c=>updateCart(c,p.id,-1))}><Minus size={14}/></button><span>{cart[p.id]}</span><button aria-label={`Aumentar cantidad de ${p.name}`} disabled={cart[p.id]>=99} onClick={()=>setCart(c=>updateCart(c,p.id,1))}><Plus size={14}/></button><button className="remove" aria-label={`Eliminar ${p.name}`} onClick={()=>setCart(c=>updateCart(c,p.id,-c[p.id]))}><Trash2 size={15}/></button></div></div></div>)}</div><div className="cart-bottom"><div className="subtotal"><span>Total estimado</span><strong>{pricedCount?money(total):'Por confirmar'}</strong></div>{hasUnpriced&&<p>Los productos sin precio y el costo del envío se cotizan antes del pago.</p>}<p>Disponibilidad, envío y total final se confirman por WhatsApp.</p><button className="gold-button checkout-button" onClick={()=>{setCartOpen(false);setCheckoutOpen(true)}}>Continuar al checkout</button><a className="gold-button" href={whatsapp(order)} target="_blank" rel="noopener noreferrer"><MessageCircle size={18}/> Consultar pedido por WhatsApp</a><button className="text-button" onClick={()=>setCartOpen(false)}>Seguir comprando</button></div></>}</SheetContent></Sheet>
 <Dialog open={checkoutOpen} onOpenChange={setCheckoutOpen}><DialogContent className="checkout-dialog"><DialogTitle className="panel-title">Finaliza tu selección</DialogTitle><DialogDescription>Completa tus datos para coordinar el pedido por WhatsApp. Confirmaremos disponibilidad, total y forma de pago antes de cobrar.</DialogDescription><form onSubmit={e=>{e.preventDefault();if(!count)return;const message=order+`\n\nNombre: ${customer.name.trim()}\nTeléfono: ${customer.phone.trim()}\nDirección de entrega: ${customer.address.trim()}\nMétodo de pago preferido: ${customer.payment}`;window.open(whatsapp(message),'_blank','noopener,noreferrer')}}><div className="checkout-summary"><span>{count} {count===1?'producto':'productos'}</span><strong>{pricedCount?money(total):'Total por confirmar'}{hasUnpriced&&pricedCount>0?' + por cotizar':''}</strong></div><label>Nombre completo<input required autoComplete="name" maxLength={100} value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})}/></label><label>Teléfono<input required type="tel" autoComplete="tel" minLength={8} maxLength={25} value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/></label><label>Dirección de entrega<textarea required autoComplete="street-address" maxLength={600} rows={3} placeholder="Provincia, cantón, distrito y señas" value={customer.address} onChange={e=>setCustomer({...customer,address:e.target.value})}/></label><fieldset><legend>Método de pago preferido</legend><RadioGroup value={customer.payment} onValueChange={value=>setCustomer({...customer,payment:String(value)})}>{['SINPE Móvil','Tarjeta de débito','Tarjeta de crédito'].map(method=><label className="payment-option" key={method}><RadioGroupItem value={method}/>{method}</label>)}</RadioGroup></fieldset><p className="checkout-note">Envío por mensajería privada. No se realiza ningún cobro en esta página. Al continuar se abrirá WhatsApp con tu pedido y estos datos; podrás revisarlos antes de enviarlos.</p><button className="gold-button" type="submit" disabled={!count}>Continuar por WhatsApp</button></form></DialogContent></Dialog>
 <Dialog open={searchOpen} onOpenChange={setSearchOpen}><DialogContent className="search-dialog"><DialogTitle className="panel-title">Encuentra tu fragancia</DialogTitle><DialogDescription>Busca por nombre o marca.</DialogDescription><form onSubmit={e=>{e.preventDefault();setSearchOpen(false);router.push('/perfumes?q='+encodeURIComponent(query))}}><label htmlFor="perfume-search" className="sr-only">Nombre o marca del perfume</label><div className="search-input"><Search size={20}/><input id="perfume-search" placeholder="Prueba con Dior, Chanel…" value={query} onChange={e=>{setQuery(e.target.value);setCategory('Todos')}} autoComplete="off" autoFocus/></div><button className="gold-button" type="submit">Ver resultados</button></form></DialogContent></Dialog>
 <Dialog open={accountOpen} onOpenChange={setAccountOpen}><DialogContent className="search-dialog"><DialogTitle className="panel-title">Compra con atención personal</DialogTitle><DialogDescription>No necesitas una cuenta. Elige tus perfumes, agrégalos al carrito y consulta tu pedido por WhatsApp. Nuestro equipo te ayudará a confirmar la disponibilidad y coordinar el pago y envío.</DialogDescription><a className="gold-button" href={contactUrl} target="_blank" rel="noopener noreferrer">Hablar con Soluna</a></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={open=>{if(!open)setDetail(null)}}><DialogContent className="detail-dialog">{detail&&<><ProductPhoto product={detail}/><DialogTitle className="panel-title">{detail.name}</DialogTitle><DialogDescription>{detail.category} · {concentration(detail)} · {detail.size} · Consulta la disponibilidad con nuestro equipo.</DialogDescription><strong className="detail-price">{detail.price?money(detail.price):'Consultar precio'}</strong><button className="gold-button" onClick={()=>{add(detail.id);setDetail(null);setCartOpen(true)}}>Agregar al carrito</button></>}</DialogContent></Dialog>
 </main>;
}

