'use client';
import {useEffect,useState,type CSSProperties} from 'react';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import {Truck,ShieldCheck,MessageCircle,Search,ShoppingBag,ChevronLeft,ChevronRight,Heart,BadgeCheck,SprayCan,Plus,Minus,Trash2,X,Pause,Play,ArrowUpRight,SlidersHorizontal,Globe} from 'lucide-react';
import {Sheet,SheetContent,SheetTitle,SheetDescription,SheetClose} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {useCart} from '@/components/cart-provider';
import {useLanguage} from '@/components/language-provider';
import {SolunaFooter} from '@/components/soluna-footer';
import {CatalogFilters} from '@/components/catalog-filters';
import {products,womenBrands,menGroups,money,filterProducts,updateCart,type Product} from '@/lib/catalog';
import {applyFilters,concentrationOf,filterCount,emptyFilters,type Filters} from '@/lib/catalog-filters';
import productImages from '@/lib/product-images.json';

function Photo({x,y,w,h,label,className=''}:{x?:number;y:number;w:number;h:number;label:string;className?:string}){
 const {t}=useLanguage();
 if(x===undefined)return <div className="perfume-identity"><span>SOLUNA</span><i aria-hidden="true"/><strong>{label}</strong><small>{t('FOTO POR CONFIRMAR','PHOTO TO BE CONFIRMED')}</small></div>;
 return <div className={`photo ${className}`} role="img" aria-label={label} style={{aspectRatio:`${w}/${h}`,'--photo-ratio':`${w}/${h}`} as CSSProperties}><img src="/soluna-reference.png" alt="" draggable={false} style={{width:`${1222/w*100}%`,maxWidth:'none',left:`${-x/w*100}%`,top:`${-y/h*100}%`}}/></div>;
}
function ProductPhoto({product}:{product:Product}){const image=(productImages as Record<string,{src:string}>)[product.id];return image?<div className="product-image"><img src={image.src} alt={product.name} loading="lazy"/></div>:<Photo x={product.x} y={product.y??883} w={164} h={product.y?183:164} label={product.name}/>}
const paths:Record<string,string>={Hombre:'/hombre',Mujer:'/mujer',Unisex:'/unisex',Todos:'/perfumes','Más vendidos':'/mas-vendidos',Nuevos:'/nuevos'};
const whatsapp=(text:string)=>'https://wa.me/50686190302?text='+encodeURIComponent(text);

export default function Storefront({collection}:{collection?:string}){
 const router=useRouter();const {t,language,setLanguage}=useLanguage();const {cart,setCart}=useCart();
 const [query,setQuery]=useState('');const [searchQuery,setSearchQuery]=useState('');
 const [searchOpen,setSearchOpen]=useState(false);const [cartOpen,setCartOpen]=useState(false);const [checkoutOpen,setCheckoutOpen]=useState(false);const [filterOpen,setFilterOpen]=useState(false);
 const [filters,setFilters]=useState<Filters>(emptyFilters);const [detail,setDetail]=useState<Product|null>(null);const [notice,setNotice]=useState(false);
 const [customer,setCustomer]=useState({name:'',phone:'',address:'',payment:'sinpe'});
 const [slide,setSlide]=useState(0);const [playing,setPlaying]=useState(true);const [interacting,setInteracting]=useState(false);
 const category=collection??'Más vendidos';const allCatalog=collection==='Todos';const grouped=category==='Hombre'||category==='Mujer';
 const categoryLabel=(value:string)=>({Hombre:t('Hombre','Men'),Mujer:t('Mujer','Women'),Todos:t('Ver todo','Shop all'),'Más vendidos':t('Más vendidos','Bestsellers'),Nuevos:t('Nuevos','New arrivals'),Unisex:'Unisex'}[value]??value);
 const sizeText=(p:Product)=>p.size==='Consultar presentación'?t('Tamaño por consultar','Size on request'):p.size;
 const concentrationText=(p:Product)=>({edp:'Eau de Parfum · EDP',edt:'Eau de Toilette · EDT',parfum:'Parfum',unknown:t('Concentración por consultar','Concentration on request')}[concentrationOf(p)]);
 const priceText=(p:Product)=>p.price!==null?money(p.price):t('Consultar precio','Price on request');
 const selected=applyFilters(filterProducts(category,query),allCatalog?filters:emptyFilters());
 const activeFilters=filterCount(filters);const groups=category==='Mujer'?womenBrands:menGroups;
 const groupItems=(brand:string)=>selected.filter(p=>p.brand===brand||(brand==='Árabes'&&p.id==='men-odyssey-mandarin-sky'));
 const cartProducts=products.filter(p=>cart[p.id]);const count=Object.values(cart).reduce((n,q)=>n+q,0);
 const pricedCount=cartProducts.filter(p=>p.price!==null).length;const total=cartProducts.reduce((n,p)=>n+(p.price??0)*cart[p.id],0);const unpriced=cartProducts.some(p=>p.price===null);
 const totalText=pricedCount?money(total):t('Por confirmar','To be confirmed');
 const contactUrl=whatsapp(t('¡Hola, Soluna! Me gustaría recibir asesoría para elegir un perfume.','Hello, Soluna! I would love some help choosing a fragrance.'));
 const order=t('¡Hola, Soluna! Quisiera consultar este pedido:','Hello, Soluna! I would like to check this order:')+'\n\n'+cartProducts.map(p=>`${cart[p.id]} × ${p.name} (${concentrationText(p)} · ${sizeText(p)}) — ${p.price!==null?money(p.price*cart[p.id]):t('Por cotizar','To be quoted')}`).join('\n')+'\n\n'+t('Total estimado: ','Estimated total: ')+totalText+(unpriced?t(' + productos por cotizar',' + items to be quoted'):'')+'\n'+t('Confirmar disponibilidad, pago y envío.','Please confirm availability, payment and delivery.');
 const slides=[
  {first:t('Fragancias que','Fragrances that'),second:t('dejan','leave an'),accent:t('huella.','impression.'),subtitle:t('Perfumes 100% originales.','100% authentic perfumes.'),category:'Todos'},
  {first:t('Tu esencia.','Your essence.'),second:t('Tu','Your'),accent:t('estilo.','signature.'),subtitle:t('Encuentra el aroma que habla de ti.','Find the scent that speaks for you.'),category:'Hombre'},
  {first:t('Un aroma','A scent'),second:t('para','to'),accent:t('recordar.','remember.'),subtitle:t('Descubre nuestra colección de mujer.','Discover our collection for her.'),category:'Mujer'},
 ];
 function browse(value:string){setSearchOpen(false);router.push(paths[value]??'/perfumes')}
 function add(id:string){setCart(current=>updateCart(current,id,1));setNotice(true)}
 useEffect(()=>{setQuery(new URLSearchParams(window.location.search).get('q')??'');setFilters(emptyFilters());},[collection]);
 useEffect(()=>{if(!collection&&(location.hash==='#hombre'||location.hash==='#mujer'))router.replace(location.hash==='#hombre'?'/hombre':'/mujer');},[collection,router]);
 useEffect(()=>{document.title=collection?`${categoryLabel(collection)} | Soluna Fragrance`:t('Soluna Perfumería | Fragancias que dejan huella','Soluna Fragrance | Fragrances that leave an impression')},[language,collection]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(false),3000);return()=>clearTimeout(timer)},[notice]);
 useEffect(()=>{const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');if(reduced.matches)setPlaying(false);const change=()=>{if(reduced.matches)setPlaying(false)};reduced.addEventListener('change',change);return()=>reduced.removeEventListener('change',change)},[]);
 useEffect(()=>{if(collection||!playing||interacting)return;const timer=setInterval(()=>{if(!document.hidden)setSlide(s=>(s+1)%3)},6500);return()=>clearInterval(timer)},[collection,playing,interacting]);
 useEffect(()=>{
  type Tool={name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown};
  const context=(document as Document & {modelContext?:{registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  const tool:Tool={name:'filter_perfume_catalog',description:'Navigate to a Soluna collection with an optional name or brand search. Does not modify the cart or place an order.',inputSchema:{type:'object',properties:{category:{type:'string',enum:Object.keys(paths)},query:{type:'string'}},required:['category'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){const value=input as {category:string;query?:string};if(!value||!Object.hasOwn(paths,value.category)||(value.query!==undefined&&typeof value.query!=='string'))throw new Error('Invalid filter');router.push(paths[value.category]+'?q='+encodeURIComponent(value.query??''));setQuery(value.query??'');return {category:value.category,products:filterProducts(value.category,value.query??'').map(p=>({id:p.id,name:p.name,price:p.price}))}}};
  try{void Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort();
 },[router]);
 const closeDialog=<DialogClose className="modal-close" aria-label={t('Cerrar','Close')}><X size={20}/></DialogClose>;
 const renderProduct=(p:Product)=><article className="product" key={p.id}><button className="product-photo-button" aria-label={`${t('Ver','View')} ${p.name}`} onClick={()=>setDetail(p)}><ProductPhoto product={p}/></button><h3><button onClick={()=>setDetail(p)}>{p.name}</button></h3>{collection&&p.featured&&<span className="featured-label">★ {t('Destacado','Featured')}</span>}{collection&&<p className="concentration">{concentrationText(p)}</p>}<p>{sizeText(p)}</p><strong>{priceText(p)}</strong><button className="add-button" onClick={()=>add(p.id)}>{cart[p.id]?t(`Agregar otro · ${cart[p.id]} en carrito`,`Add another · ${cart[p.id]} in cart`):t('Agregar al carrito','Add to cart')}</button></article>;
 const collectionTitle=category==='Todos'?t('Todas las fragancias','All fragrances'):category==='Hombre'?t('Perfumes de hombre','Fragrances for him'):category==='Mujer'?t('Perfumes de mujer','Fragrances for her'):categoryLabel(category);
 return <main>
 <a className="skip-link" href="#coleccion">{t('Saltar al catálogo','Skip to catalogue')}</a>
 <header className="masthead"><div className="shipping"><Truck size={18}/><span>{t('Envíos a todo Costa Rica','Delivery across Costa Rica')} 🇨🇷</span></div><Link className="brand" href="/" aria-label={t('Soluna, inicio','Soluna, home')}><Photo x={483} y={0} w={153} h={78} label="Soluna Fragrance"/></Link><div className="header-actions"><a className="whatsapp-top" href={contactUrl} target="_blank" rel="noopener noreferrer"><MessageCircle size={17}/>+506 8619 0302</a><div className="language-switch" role="group" aria-label={t('Idioma','Language')}><Globe size={14}/>{(['es','en'] as const).map(value=><button key={value} onClick={()=>setLanguage(value)} aria-pressed={language===value} aria-label={value==='es'?'Español':'English'}>{value.toUpperCase()}</button>)}</div><button aria-label={t('Buscar perfumes','Search fragrances')} onClick={()=>{setSearchQuery(query);setSearchOpen(true)}}><Search/></button><button className="bag" aria-label={t(`Abrir carrito, ${count} productos`,`Open cart, ${count} items`)} onClick={()=>setCartOpen(true)}><ShoppingBag/><span>{count}</span></button></div></header>
 <nav aria-label={t('Navegación principal','Main navigation')}>{['Inicio','Hombre','Mujer','Unisex','Más vendidos','Nuevos','Contacto'].map(n=><Link key={n} className={(!collection&&n==='Inicio')||collection===n?'active':''} href={n==='Inicio'?'/':n==='Contacto'?'#contacto':paths[n]}>{n==='Inicio'?t('Inicio','Home'):n==='Contacto'?t('Contacto','Contact'):categoryLabel(n)}</Link>)}</nav>
 {collection&&<div className="collection-intro content"><Link href="/">{t('Inicio','Home')}</Link><span>/</span><span>{categoryLabel(category)}</span><p>Soluna Fragrance</p><h1>{collectionTitle}</h1></div>}
 {!collection&&<>
 <section className="hero cinematic-hero" id="inicio" aria-roledescription={t('carrusel','carousel')} aria-label={t('Colecciones Soluna','Soluna collections')} onMouseEnter={()=>setInteracting(true)} onMouseLeave={()=>setInteracting(false)} onFocusCapture={()=>setInteracting(true)} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setInteracting(false)}}>
 <div className={`hero-layer ${slide===0?'is-visible':''}`} aria-hidden="true"><Photo x={505} y={131} w={715} h={311} label="" className="hero-photo"/></div><div className={`hero-layer ${slide===1?'is-visible':''}`} aria-hidden="true"><img className="hero-bg" src="/images/hero-gold-splash.png" alt=""/></div><div className={`hero-layer ${slide===2?'is-visible':''}`} aria-hidden="true"><img className="hero-bg" src="/images/hero-rose.png" alt=""/></div><div className="hero-shade"/>
 <div className="hero-copy" key={slide}><p className="eyebrow">{t('Soluna perfumería','Soluna fragrance')} <span>—</span></p><h1>{slides[slide].first}<br/>{slides[slide].second} <em>{slides[slide].accent}</em></h1><p className="hero-subtitle">{slides[slide].subtitle}</p><Link className="gold-button" href={paths[slides[slide].category]}>{t('Ver colección','Explore collection')}<ArrowUpRight size={15}/></Link></div><button className="hero-arrow previous" aria-label={t('Colección anterior','Previous collection')} onClick={()=>setSlide(s=>(s+2)%3)}><ChevronLeft/></button><button className="hero-arrow next" aria-label={t('Siguiente colección','Next collection')} onClick={()=>setSlide(s=>(s+1)%3)}><ChevronRight/></button><div className="carousel-bottom"><span className="slide-counter">0{slide+1}<i/>03</span><div className="dots">{slides.map((s,i)=><button key={i} className={i===slide?'selected':''} aria-label={t(`Ver colección ${i+1}`,`View collection ${i+1}`)} aria-pressed={i===slide} onClick={()=>setSlide(i)}/>)}</div><button className="carousel-play" aria-label={playing?t('Pausar carrusel','Pause carousel'):t('Reanudar carrusel','Play carousel')} aria-pressed={!playing} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={14}/>:<Play size={14}/>}</button></div>
 </section>
 <section className="benefits" aria-label={t('Beneficios','Benefits')}>{[{Icon:SprayCan,title:t('100% originales','100% authentic'),a:t('Garantizamos la autenticidad','Authenticity you can trust'),b:t('de todos nuestros perfumes.','in every fragrance.')},{Icon:Truck,title:t('Envíos rápidos','Fast delivery'),a:t('Mensajería privada','Private courier'),b:t('en todo Costa Rica.','across Costa Rica.')},{Icon:ShieldCheck,title:t('Compra segura','Shop with confidence'),a:t('Atención y confianza','Personal service'),b:t('en cada compra.','with every purchase.')},{Icon:MessageCircle,title:t('Atención personalizada','Personal attention'),a:t('Escríbenos por WhatsApp','Message us on WhatsApp'),b:t('y te asesoramos.','and find your fragrance.')}].map(({Icon,title,a,b})=><div className="benefit" key={title}><Icon/><h3>{title}</h3><p>{a}<br/>{b}</p></div>)}</section>
 <section className="categories content"><h2 className="section-title">{t('Explora por categoría','Explore by category')}</h2><div className="category-grid refined-categories">{[{name:'Hombre',x:60,w:160,tone:'him',sub:t('Carácter y presencia','Character & presence')},{name:'Mujer',x:422,w:164,tone:'her',sub:t('Elegancia que inspira','Elegance that inspires')},{name:'Unisex',x:809,w:169,tone:'unisex',sub:t('Una esencia sin límites','A scent without limits')}].map(c=><Link href={paths[c.name]} className={`category refined-category ${c.tone}`} key={c.name}><div className="category-art"><Photo x={c.x} y={632} w={c.w} h={183} label={t(`Perfume de ${c.name.toLowerCase()}`,`${categoryLabel(c.name)} fragrance`)}/></div><div className="category-copy"><span>{c.sub}</span><h3>{categoryLabel(c.name)}</h3><span className="category-button">{t('Ver más','Discover')}<ArrowUpRight size={14}/></span></div></Link>)}</div></section>
 </>}
 <section className={`catalog content ${collection?'collection-page':''} ${allCatalog?'all-catalog':''}`} id="coleccion"><div className="catalog-heading"><h2 className="section-title">{query?t(`Resultados para “${query}”`,`Results for “${query}”`):categoryLabel(category)}</h2>{!collection&&<Link className="view-all" href="/perfumes">{t('Ver todo','Shop all')}<ArrowUpRight size={15}/></Link>}</div>
 {collection&&<div className="catalog-toolbar"><p role="status">{selected.length} {t('fragancias','fragrances')}{activeFilters>0&&allCatalog?` · ${activeFilters} ${t('filtros','filters')}`:''}</p><label className="collection-search"><Search size={17}/><input aria-label={t('Buscar perfume o marca','Search fragrance or brand')} placeholder={t('Buscar perfume o marca…','Search fragrance or brand…')} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label={t('Limpiar búsqueda','Clear search')} onClick={()=>setQuery('')}><X size={16}/></button>}</label>{allCatalog&&<button className="mobile-filter-toggle" onClick={()=>setFilterOpen(true)}><SlidersHorizontal size={16}/>{t('Filtros','Filters')} ({activeFilters})</button>}</div>}
 {grouped&&<div className="brand-links" aria-label={t('Ir a una marca','Jump to a brand')}>{groups.map((g,i)=>groupItems(g.brand).length?<a key={g.brand} href={`#marca-${i}`}>{g.brand==='Árabes'?t('Árabes','Arabian fragrances'):g.brand}</a>:null)}</div>}
 <div className={allCatalog?'catalog-layout':'catalog-results-wrap'}>{allCatalog&&<aside className="desktop-filters"><CatalogFilters filters={filters} onChange={setFilters}/></aside>}<div className="catalog-results">{grouped?groups.map((g,i)=>{const items=groupItems(g.brand);return items.length?<section className="brand-section" id={`marca-${i}`} key={g.brand}><header><span>{String(i+1).padStart(2,'0')}</span><h3>{g.brand==='Árabes'?t('Árabes','Arabian fragrances'):g.brand}</h3><small>{items.length} {t('fragancias','fragrances')}</small></header><div className="product-grid brand-products">{items.map(renderProduct)}</div></section>:null}):<div className={`product-grid ${allCatalog?'filtered-products':''}`}>{selected.map(renderProduct)}</div>}{selected.length===0&&<div className="empty-state"><Search/><h3>{t('No encontramos esa fragancia','No fragrances found')}</h3><p>{t('Prueba con otra marca o ajusta los filtros.','Try another brand or adjust your filters.')}</p><button className="gold-button" onClick={()=>{setQuery('');setFilters(emptyFilters())}}>{t('Limpiar búsqueda y filtros','Clear search and filters')}</button></div>}</div></div>
 </section>
 <section className="contact-strip"><MessageCircle className="contact-icon"/><div><p>{t('¿Dudas o consultas?','Need a little guidance?')}</p><h2>{t('Tu próxima fragancia empieza aquí.','Your next fragrance starts here.')}</h2><span>{t('Te ayudamos a encontrar un aroma que se sienta tuyo.','Let us help you find a scent that feels like you.')}</span></div><a className="gold-button" href={contactUrl} target="_blank" rel="noopener noreferrer">{t('Escribir por WhatsApp','Chat on WhatsApp')}<ArrowUpRight size={15}/></a></section>
 <SolunaFooter/>
 <a className="floating-whatsapp" href={contactUrl} target="_blank" rel="noopener noreferrer" aria-label={t('Consultar o comprar por WhatsApp','Ask or shop on WhatsApp')}><MessageCircle/></a>
 <div className="announcement" role="status" aria-live="polite">{notice&&<span><BadgeCheck size={18}/>{t('Perfume agregado al carrito','Fragrance added to cart')}<button onClick={()=>{setCartOpen(true);setNotice(false)}}>{t('Ver carrito','View cart')}</button></span>}</div>
 <Sheet open={cartOpen} onOpenChange={setCartOpen}><SheetContent className="cart-panel" showCloseButton={false}><SheetClose className="modal-close" aria-label={t('Cerrar carrito','Close cart')}><X size={20}/></SheetClose><SheetTitle className="panel-title">{t('Tu carrito','Your cart')} <span>({count})</span></SheetTitle><SheetDescription>{t('Una selección que deja huella.','A selection that leaves an impression.')}</SheetDescription>{count===0?<div className="empty-state"><ShoppingBag/><h3>{t('Tu próxima fragancia te espera','Your next fragrance awaits')}</h3><p>{t('Explora la colección y agrega tus favoritos.','Explore the collection and add your favourites.')}</p><button className="gold-button" onClick={()=>{setCartOpen(false);browse('Todos')}}>{t('Explorar perfumes','Explore fragrances')}</button></div>:<><div className="cart-items">{cartProducts.map(p=><div className="cart-item" key={p.id}><ProductPhoto product={p}/><div><h3>{p.name}</h3><p>{sizeText(p)} · {priceText(p)}</p><div className="quantity"><button aria-label={`${t('Reducir cantidad de','Decrease quantity for')} ${p.name}`} onClick={()=>setCart(c=>updateCart(c,p.id,-1))}><Minus size={14}/></button><span>{cart[p.id]}</span><button disabled={cart[p.id]>=99} aria-label={`${t('Aumentar cantidad de','Increase quantity for')} ${p.name}`} onClick={()=>setCart(c=>updateCart(c,p.id,1))}><Plus size={14}/></button><button className="remove" aria-label={`${t('Eliminar','Remove')} ${p.name}`} onClick={()=>setCart(c=>updateCart(c,p.id,-c[p.id]))}><Trash2 size={15}/></button></div></div></div>)}</div><div className="cart-bottom"><div className="subtotal"><span>{t('Total estimado','Estimated total')}</span><strong>{totalText}</strong></div>{unpriced&&<p>{t('Los productos sin precio se cotizan antes del pago.','Unpriced items will be quoted before payment.')}</p>}<p>{t('Disponibilidad, envío y total final se confirman por WhatsApp.','Availability, delivery and the final total are confirmed via WhatsApp.')}</p><button className="gold-button checkout-button" onClick={()=>{setCartOpen(false);setCheckoutOpen(true)}}>{t('Continuar al checkout','Continue to checkout')}</button><a className="text-button" href={whatsapp(order)} target="_blank" rel="noopener noreferrer">{t('Consultar pedido por WhatsApp','Ask about this order on WhatsApp')}</a><button className="text-button" onClick={()=>setCartOpen(false)}>{t('Seguir comprando','Continue shopping')}</button></div></>}</SheetContent></Sheet>
 <Sheet open={filterOpen} onOpenChange={setFilterOpen}><SheetContent side="left" className="filter-panel" showCloseButton={false}><SheetClose className="modal-close" aria-label={t('Cerrar filtros','Close filters')}><X size={20}/></SheetClose><SheetTitle className="panel-title">{t('Encuentra tu fragancia','Find your fragrance')}</SheetTitle><SheetDescription>{t('Filtra por marca, género, precio y tamaño.','Filter by brand, gender, price and size.')}</SheetDescription><CatalogFilters filters={filters} onChange={setFilters}/><button className="gold-button" onClick={()=>setFilterOpen(false)}>{t(`Ver ${selected.length} resultados`,`View ${selected.length} results`)}</button></SheetContent></Sheet>
 <Dialog open={checkoutOpen} onOpenChange={setCheckoutOpen}><DialogContent className="checkout-dialog" showCloseButton={false}>{closeDialog}<DialogTitle className="panel-title">{t('Finaliza tu selección','Complete your selection')}</DialogTitle><DialogDescription>{t('Completa tus datos para coordinar el pedido por WhatsApp. Confirmaremos el total antes de cobrar.','Enter your details to arrange your order via WhatsApp. We will confirm the total before payment.')}</DialogDescription><form onSubmit={e=>{e.preventDefault();if(!count||!customer.name.trim()||!customer.address.trim())return;const payment=customer.payment==='sinpe'?'SINPE Móvil':customer.payment==='debit'?t('Tarjeta de débito','Debit card'):t('Tarjeta de crédito','Credit card');window.open(whatsapp(order+`\n\n${t('Nombre','Name')}: ${customer.name.trim()}\n${t('Teléfono','Phone')}: ${customer.phone.trim()}\n${t('Dirección','Address')}: ${customer.address.trim()}\n${t('Pago preferido','Preferred payment')}: ${payment}`),'_blank','noopener,noreferrer')}}><div className="checkout-summary"><span>{count} {t('productos','items')}</span><strong>{totalText}{unpriced&&pricedCount>0?t(' + por cotizar',' + to be quoted'):''}</strong></div><label>{t('Nombre completo','Full name')}<input required autoComplete="name" maxLength={100} value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})}/></label><label>{t('Teléfono','Phone')}<input required type="tel" autoComplete="tel" minLength={8} maxLength={25} value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/></label><label>{t('Dirección de entrega','Delivery address')}<textarea required autoComplete="street-address" rows={3} maxLength={600} placeholder={t('Provincia, cantón, distrito y señas','Province, canton, district and directions')} value={customer.address} onChange={e=>setCustomer({...customer,address:e.target.value})}/></label><fieldset><legend>{t('Método de pago preferido','Preferred payment method')}</legend><RadioGroup value={customer.payment} onValueChange={value=>setCustomer({...customer,payment:String(value)})}>{[['sinpe','SINPE Móvil'],['debit',t('Tarjeta de débito','Debit card')],['credit',t('Tarjeta de crédito','Credit card')]].map(([value,label])=><label key={value} className="payment-option"><RadioGroupItem value={value}/>{label}</label>)}</RadioGroup></fieldset><p className="checkout-note">{t('Envío por mensajería privada. Esta página no realiza cobros. WhatsApp abrirá tu pedido y estos datos para revisarlos antes de enviarlos.','Delivery by private courier. This page does not charge payments. WhatsApp will open your order and these details for review before you send them.')}</p><button className="gold-button" type="submit" disabled={!count}>{t('Continuar por WhatsApp','Continue on WhatsApp')}</button></form></DialogContent></Dialog>
 <Dialog open={searchOpen} onOpenChange={setSearchOpen}><DialogContent className="search-dialog" showCloseButton={false}>{closeDialog}<DialogTitle className="panel-title">{t('Encuentra tu fragancia','Find your fragrance')}</DialogTitle><DialogDescription>{t('Busca por nombre o marca.','Search by name or brand.')}</DialogDescription><form onSubmit={e=>{e.preventDefault();setSearchOpen(false);setQuery(searchQuery);router.push('/perfumes?q='+encodeURIComponent(searchQuery))}}><label htmlFor="perfume-search" className="sr-only">{t('Nombre o marca del perfume','Fragrance name or brand')}</label><div className="search-input"><Search size={20}/><input id="perfume-search" placeholder={t('Prueba con Dior, Chanel…','Try Dior, Chanel…')} value={searchQuery} onChange={e=>setSearchQuery(e.target.value)} autoComplete="off" autoFocus/></div><button className="gold-button" type="submit">{t('Ver resultados','View results')}</button></form></DialogContent></Dialog>
 <Dialog open={!!detail} onOpenChange={open=>{if(!open)setDetail(null)}}><DialogContent className="detail-dialog" showCloseButton={false}>{closeDialog}{detail&&<><ProductPhoto product={detail}/><DialogTitle className="panel-title">{detail.name}</DialogTitle><DialogDescription>{categoryLabel(detail.category)} · {concentrationText(detail)} · {sizeText(detail)}. {t('Consulta la disponibilidad con nuestro equipo.','Check availability with our team.')}</DialogDescription><strong className="detail-price">{priceText(detail)}</strong><button className="gold-button" onClick={()=>{add(detail.id);setDetail(null);setCartOpen(true)}}>{t('Agregar al carrito','Add to cart')}</button></>}</DialogContent></Dialog>
 </main>;
}

