import type {Product} from './catalog';
export type Filters={brands:string[];genders:string[];sizes:string[];concentrations:string[];occasions:string[];families:string[];priceRange:[number,number]};
export const emptyFilters=():Filters=>({brands:[],genders:[],sizes:[],concentrations:[],occasions:[],families:[],priceRange:[0,235000]});
export function brandOf(p:Product):string {if(p.brand==='Odyssey')return 'Armaf';if(p.brand==='Árabes')return p.name.startsWith('Maison Alhambra')?'Maison Alhambra':p.name.split(' ')[0];if(p.brand)return p.brand;return ({sauvage:'Dior',bleu:'Chanel',million:'Paco Rabanne',acqua:'Giorgio Armani',gypsy:'Byredo'} as Record<string,string>)[p.id]??p.name.split(' ')[0]}
export function concentrationOf(p:Product):string {if(['good-girl','black-opium'].includes(p.id)||/\bEDP\b|Eau de Parfum/i.test(p.name))return 'edp';if(/\bEDT\b|Eau de Toilette/i.test(p.name))return 'edt';if(p.id==='bleu')return 'parfum';return 'unknown'}
export function sizeOf(p:Product):string {const match=p.size.match(/^(\d+)\s*ml$/i);return match?match[1]:'unknown'}
export function applyFilters(items:Product[],filters:Filters){const fullPrice=filters.priceRange[0]===0&&filters.priceRange[1]===235000;return items.filter(p=>(!filters.brands.length||filters.brands.includes(brandOf(p)))&&(!filters.genders.length||filters.genders.includes(p.category))&&(!filters.sizes.length||filters.sizes.includes(sizeOf(p)))&&(!filters.concentrations.length||filters.concentrations.includes(concentrationOf(p)))&&(!filters.occasions.length||filters.occasions.includes('unknown'))&&(!filters.families.length||filters.families.includes('unknown'))&&(p.price===null?fullPrice:p.price>=filters.priceRange[0]&&p.price<=filters.priceRange[1]))}
export const filterCount=(filters:Filters)=>filters.brands.length+filters.genders.length+filters.sizes.length+filters.concentrations.length+filters.occasions.length+filters.families.length+(filters.priceRange[0]!==0||filters.priceRange[1]!==235000?1:0);

